### ISSUE TITLE
Vaadin component changes the value to empty string or null in DOM

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#110]
### Actual

`vaadin-date-picker`, which is a Polymer element, is wrapped in `uni-date-picker`.

When `uni-date-picker` is detached from DOM, the input value that is bound to the date picker becomes empty string or null. that change is picked up by Palindrom and propagated to the server.

### Desired

When uni-date-picker is detached, the input value should remain unchanged.

**Comment by warpech** [comment]
Repo with KitchenSink:

- go to https://kitchensink.starcounter.io/KitchenSink/DatePicker
- change the page
- go to another page in the left menu

You will see an exception in the console

**Comment by malx122** [comment]
<vaadin-dropdown-menu id="selectUser" placeholder="no user signed in"  slot="co-common/test_user/component" class="wide" value="{{model.LoginUser$}}">
             <template>
               <vaadin-list-box>
                 <template is="dom-repeat" items="[[model.TestUsers]]">
                   <vaadin-item value="[[item.Username]]">
                     <div style="display:flex;align-items:center" title="[[item.Name]]">
                       <co-avatar url$="[[item.Avatar]]" size="20" style="margin:0px 3px;"></co-avatar>
                       <span>[[item.Name]]</span>
                     </div>
                   </vaadin-item>
                 </template>
               </vaadin-list-box>
             </template>
           </vaadin-dropdown-menu>

**Comment by tomalec** [comment]
I was able to reproduce setting to `""`  at https://github.com/Starcounter/KitchenSink/tree/uniform.css/issues/110-vaadin-changes-to-empty

(with hidden error as it's not propagated due to lack of `palindrom-error-catcher` https://github.com/Starcounter/StarcounterClientFiles/pull/88)

### Steps to reproduce:
1. Build and run KitchenSink at [`uniform.css/issues/110-vaadin-changes-to-empty` branch](https://github.com/Starcounter/KitchenSink/tree/uniform.css/issues/110-vaadin-changes-to-empty),
2. Go to http://localhost:8080/KitchenSink/Radiolist,
3. Open network->WS tab in dev tools,
4. Click on any link in the left menu (navigate away)

### Expected behavior
No error should be sent from the server, no change should be made to the value of a selected item.

### Actual behavior
Client sends patch
```
[{"op":"replace","path":"/_ver#c$","value":2},{"op":"test","path":"/_ver#s","value":2},{"op":"replace","path":"/KitchenSink_0/CurrentPage/KitchenSink_0/LoginUser$","value":""}]
```
Server throws an error
```
Unknown property in path. Patch: '{"op":"replace","path":"/KitchenSink_0/CurrentPage/KitchenSink_0/LoginUser$","value":""}'. Property: 'LoginUser$'. Viewmodel versions: {client (_ver#c$): 2, clients serverversion: 2, server (_ver#s): 2}.
```

**Comment by tomalec** [comment]
Isloeted it to just `vaadin-dropdown-menu` problem, even without Proxies
https://github.com/vaadin/vaadin-dropdown-menu/issues/130

**Comment by tomalec** [comment]
The issue is now fixed, merged in latest `master` of https://github.com/vaadin/vaadin-dropdown-menu, and waits for the release.

**Comment by warpech** [comment]
Closing as released in https://github.com/vaadin/vaadin-dropdown-menu 1.1.0-beta1
