### ISSUE TITLE
Simplify build tool

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#22]
Webpack seems to be a little overhead for just minifying css files, it also introduces severe problems like https://github.com/Starcounter/uniform.css/issues/9#issuecomment-364141306

That's another reason why we should review built code

**Comment by warpech** [comment]
Webpack is just a bunch of plugins. 

In this case our Webpack config uses CSSNano, which internally is based on PostCss and is perhaps the best CSS minifier out there. It is fully configurable.

The problem in https://github.com/Starcounter/uniform.css/issues/9#issuecomment-364141306 was fixed by improving the configuration.

Do you still have problem with Webpack? I agree it overly complicates the build a bit. We could use CssNano directly. But right now I don't think it is worth the effort to make a change.

**Comment by tomalec** [comment]
Closing, as not needed for now. We could consider simplifying in the future.
