### ISSUE TITLE
Pagination, wrong height and incorrect background color on disabled

### ISSUE THREAD

**Issue by andwah** [Starcounter/uniform.css#52]
- The height should be 32px.
- Transparent text backgrounds.
- The devider line should be 1px with and 20px high, vertical centerd

![image](https://user-images.githubusercontent.com/2656996/36472006-b0a8b744-16f0-11e8-8a40-3034bb4e46fd.png)

**Comment by warpech** [comment]
The margin on `Next` is wrong when pagination is applied in KitchenSink:

![image](https://user-images.githubusercontent.com/566463/36782201-7f0c876e-1c78-11e8-8f4c-4c76aa2a9045.png)

I think that Uniform.css should implement the `First` and `Last` buttons in the demo, too.

----

I don't agree that we should use the word "Prev", for the below reasons: 

1. It is not a dictionary word.
2. The UI might be translated to any language, not only English.

The width of the link must not be fixed, because in other languages it might be longer. For example, in Polish it is `Poprzednie` and `Następne`.

**Comment by alshakero** [comment]
1. The margin seems be already fixed ![image](https://user-images.githubusercontent.com/17054134/41106217-de450324-6a6f-11e8-8d5c-4da87b79d13b.png)
2. [Next](https://github.com/Starcounter/uniform.css/blob/master/uniform.css#L359) and [Previous](https://github.com/Starcounter/uniform.css/blob/master/uniform.css#L332) issue already fixed. 
3. [Addressed in #114] I think that Uniform.css should implement the First and Last buttons in the demo, too.
4. The width of the link must not be fixed. I don't think it is fixed. Maybe it was fixed after this issue was created. 


I think all the issues you raise are fixed already

**Comment by alshakero** [comment]
Closing as fixed in `uni-pagination` that was released in Uniform 0.4.0.
